#!/usr/bin/env bash
# Wrapper for the caddy root LaunchDaemon: wait until every address Caddy is
# configured to `bind` actually exists on an interface, then exec caddy.
#
# THE PROBLEM. Caddy is a SYSTEM LaunchDaemon and starts pre-login. The tailnet
# address it binds (Caddyfile.d/tailnet.caddy, two site blocks) is created on a
# utun interface by the Tailscale GUI app, which starts AT login. Binding an
# address the kernel does not have yet returns EADDRNOTAVAIL ([Errno 49]) and
# Caddy aborts the WHOLE config — not just the tailnet blocks. Every `.test`
# site and metabase.iu-aws.de go down with them.
#
# STATE IT HONESTLY: this is a BOUNDED outage, not a permanent one. launchd
# retries a KeepAlive job on a 10s throttle, so caddy self-heals roughly 10s
# after the utun address appears. The include was generated Jul 29 and the last
# boot was Jul 24, so this path has never actually run — the fix is to stop
# depending on a race that happens to resolve, not to rescue a dead machine.
#
# WHY A DAEMON WRAPPER AND NOT A USER LAUNCHAGENT. Regenerating the include from
# a user agent looks equivalent and is not: a LaunchAgent fires at LOGIN, which
# is the same event that creates the address, so it cannot order itself before
# the daemon that already failed. The wait has to live in the daemon.
#
# The addresses are read from the live Caddyfile rather than hardcoded, because
# the tailnet IP is regenerated by `make caddy-tailnet` and a stale literal here
# would wait for an address that never arrives.
#
# Fails OPEN. If the wait times out, it execs caddy anyway. A wrapper that can
# refuse to start the reverse proxy when the wrapper itself is confused is worse
# than the race it replaces — and the launchd retry that covers today's failure
# still covers it.

set -u

CADDY_BIN="${CADDY_BIN:-/opt/homebrew/opt/caddy/bin/caddy}"
CADDYFILE="${CADDYFILE:-/opt/homebrew/etc/Caddyfile}"
CADDY_INCLUDE_DIR="${CADDY_INCLUDE_DIR:-/opt/homebrew/etc/Caddyfile.d}"
WAIT_SECONDS="${CADDY_WAIT_SECONDS:-120}"
POLL_SECONDS="${CADDY_POLL_SECONDS:-2}"

log() { echo "$(date '+%Y-%m-%d %H:%M:%S') caddy-wait-for-tailnet: $*"; }

# Every non-loopback literal IPv4/IPv6 the config asks Caddy to bind. Loopback
# and 0.0.0.0 always exist, so waiting on them would be a pure delay.
wanted_addrs() {
  { cat "$CADDYFILE" 2>/dev/null; cat "$CADDY_INCLUDE_DIR"/*.caddy 2>/dev/null; } \
    | awk '$1 == "bind" { for (i = 2; i <= NF; i++) print $i }' \
    | grep -Ev '^(127\.|::1$|0\.0\.0\.0$|localhost$)' \
    | sort -u
}

addr_present() {
  /sbin/ifconfig 2>/dev/null | grep -qE "(^|[[:space:]])inet6? $1([[:space:]]|%|$)"
}

missing=$(wanted_addrs)
if [ -z "$missing" ]; then
  log "no non-loopback bind addresses in the config — starting immediately"
else
  log "waiting up to ${WAIT_SECONDS}s for: $(echo "$missing" | tr '\n' ' ')"
  deadline=$(( $(date +%s) + WAIT_SECONDS ))
  while :; do
    still=""
    for a in $missing; do
      addr_present "$a" || still="$still $a"
    done
    [ -z "$still" ] && { log "all bind addresses present"; break; }
    if [ "$(date +%s)" -ge "$deadline" ]; then
      log "TIMEOUT after ${WAIT_SECONDS}s — still missing:$still. Starting caddy anyway; launchd's KeepAlive retry is the backstop." >&2
      break
    fi
    sleep "$POLL_SECONDS"
  done
fi

exec "$CADDY_BIN" run --config "$CADDYFILE"
