#!/usr/bin/env bash
set -euo pipefail

# caddy-tailnet — expose dev ports on this machine over the tailnet, via Caddy.
#
# Runs ON the dev host. Reads a declarative port list and regenerates a
# machine-local Caddy include; the generated file is deliberately NOT tracked in
# dotfiles because it names this machine's MagicDNS hostname and Tailscale IP,
# which the security rule keeps out of git. Regenerate it per machine rather
# than copying it between them.
#
# Why Caddy rather than `tailscale serve`: Tailscale issue #18827 drops
# WebSockets through serve/funnel every 10-40s, which is Vite HMR breaking on a
# timer. Caddy proxies upgrades transparently. `serve` remains right for
# always-on services (rb on :7730, the IU dashboard Funnel on :8443) — those are
# declared in dotfiles-private/tailscale-serve.<machine>.conf and are not this
# script's business.
#
# Certs come from tailscaled itself — real Let's Encrypt, auto-renewed, no local
# CA for the client to trust. Caddy runs as root, which is what lets it read
# /Library/Tailscale/sameuserproof-*.

PORTS_FILE="${CADDY_TAILNET_PORTS:-$HOME/.config/caddy-tailnet.ports}"
OUT="$(brew --prefix)/etc/Caddyfile.d/tailnet.caddy"
TS=/Applications/Tailscale.app/Contents/MacOS/Tailscale

die() { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

[[ -x "$TS" ]] || die "Tailscale.app not found — this is meant to run on the dev host"

if [[ ! -f "$PORTS_FILE" ]]; then
  mkdir -p "$(dirname "$PORTS_FILE")"
  cat > "$PORTS_FILE" <<'SEED'
# Dev ports exposed over the tailnet, one per line: PORT [label]
# Blank lines and # comments ignored. Re-run `make caddy-tailnet` after editing.
#
# The port number is the same inside and outside — Caddy binds ONLY the tailnet
# IP, so it does not collide with the dev server on 127.0.0.1:PORT.
#
# Every app served this way needs its dev server to accept the MagicDNS Host
# header (Vite 5.4.12+: server.allowedHosts) or it answers 403.

7715 argo-dashboard
7710 basalt-playground
7727 modelpick
SEED
  printf 'seeded %s — edit it and re-run\n' "$PORTS_FILE"
fi

# Live values, never hardcoded: a device rename or IP change must not silently
# leave a stale binding behind (the same failure mode tailscale-serve.sh exists
# to prevent).
HOSTN=$("$TS" status --json | python3 -c \
  'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))')
IP=$("$TS" status --json | python3 -c \
  'import json,sys; print(json.load(sys.stdin)["Self"]["TailscaleIPs"][0])')
[[ -n $HOSTN && -n $IP ]] || die "could not read this machine's tailnet identity"

mkdir -p "$(dirname "$OUT")"
{
  echo "# GENERATED by scripts/caddy-tailnet.sh — do not edit by hand."
  echo "# Machine-local: names this host's MagicDNS name + Tailscale IP, so it"
  echo "# is deliberately untracked. Source of truth for the port list:"
  echo "#   $PORTS_FILE"
  echo "#"
  echo "# bind is load-bearing: without it Caddy takes 0.0.0.0:PORT and collides"
  echo "# with the dev server already on 127.0.0.1:PORT."
  echo ""
  echo "(tailnet) {"
  echo "	bind $IP"
  echo "	tls {"
  echo "		get_certificate tailscale"
  echo "	}"
  echo "}"
  echo ""
  while read -r port label; do
    [[ -z ${port:-} || $port == \#* ]] && continue
    [[ $port =~ ^[0-9]+$ ]] || die "bad port '$port' in $PORTS_FILE"
    [[ -n ${label:-} ]] && echo "# $label"
    echo "$HOSTN:$port {"
    echo "	import tailnet"
    echo "	reverse_proxy 127.0.0.1:$port"
    echo "}"
    echo ""
  done < "$PORTS_FILE"
} > "$OUT"

caddy validate --config "$(brew --prefix)/etc/Caddyfile" --adapter caddyfile >/dev/null 2>&1 \
  || die "generated config is invalid — inspect $OUT"

caddy reload --config "$(brew --prefix)/etc/Caddyfile" --adapter caddyfile 2>/dev/null \
  || die "caddy reload failed (is Caddy running? 'brew services list')"

printf '\n  tailnet dev ports on %s\n\n' "$HOSTN"
grep -E '^[a-z0-9.-]+:[0-9]+ \{' "$OUT" | sed 's/ {//' | while read -r hostport; do
  printf '    https://%s\n' "$hostport"
done
printf '\n  Vite apps need server.allowedHosts to accept that Host header.\n\n'
